### PR TITLE
Improve triangle perspective on release logo

### PR DESCRIPTION
**Pull request by ckj**
Congrats on the Release launch. I noticed that the perspective of the Zeit triangle was a little off, so I took a stab at fixing it.

repo banner, before and after

### CODE REVIEW

**Comment by CodeTheory** [comment]
Yes! Thank you! I was going to propose this myself but have been busy. 😄 

@evilrabbit Could you approve?

**Comment by leo** [comment]
🙏

**Comment by evilrabbit** [comment]
Thank you @ckj <3 Looks Awesome!

**Comment by ckj** [comment]
Np! Glad to have helped.

**Comment by leo** [comment]
@evilrabbit Maybe we should upload the project files for open source projects?

**Pull request merged**
